export default `
<div class="the_content_wrapper">

  <h2>TERMS OF SERVICE</h2>
  <p><strong>&nbsp;</strong></p>
  <p><strong>These Terms provide that with limited exceptions covered by Section&nbsp;</strong><strong>17.3</strong><strong>&nbsp;of these Terms all disputes between you and Mr. Pengu arising out of or relating to these Terms or your use of the PLATFORM (the “Disputes”) will be resolved by BINDING ARBITRATION. For such Disputes, YOU waive YOUR RIGHT TO bring a class or representative action, or GO TO COURT under these Terms.</strong>&nbsp;Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury, and your claims must be brought individually and not as a class or representative action. Please review Section 17 (“Dispute Resolution and Arbitration”) for the details regarding your agreement to individually arbitrate any Disputes with Mr. Pengu.</p>
  <p>Thank you for your interest in the Mr. Pengu application for your mobile device (the “App”) provided to you by Mr. Pengu Inc. (“Mr. Pengu “, “us” or “we”), and our web site at&nbsp;<a href="https://mrpengu.com/">mrpengu.com</a>&nbsp;(the “Site”), as well as all related web sites, networks, and downloadable software provided by us and on which a link to these Terms of Service is displayed (collectively, together with the App and Site, our “Platform”). These Terms of Service (these “Terms”), including the&nbsp;<a href="https://mrpengu.com/privacy-policy/">Privacy Policy</a>&nbsp;incorporated into these Terms by reference and any other applicable policies and guidelines, as may be updated from time to time, govern your use of the Platform. These Terms constitute a legal agreement between you and Mr. Pengu. In order to use the Platform you must agree to these Terms.</p>
  <p>All references to “you” or “your,” as applicable, mean the person who accesses, uses, and/or participates in the Platform in any manner, and each of your heirs, assigns, and successors. If you use the Platform on behalf of an entity, organization, or company, you represent and warrant that you have the authority to bind that entity to these Terms, your acceptance of the Terms will be deemed an acceptance by that entity, and “you” and “your” herein shall refer to that entity.</p>
  <p>BY DOWNLOADING, INSTALLING, OR OTHERWISE ACCESSING OR USING THE PLATFORM, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, YOU MAY NOT USE THE PLATFORM.</p>
  <p>MR PENGU PLATFORM</p>
  <p>The Platform connects consumers with retail stores, and restaurants (“Merchants”), and with independent contractor couriers (“Couriers”), to facilitate on-demand delivery or pickup services. Through the Platform, consumers may request that merchandise or food be made available for pick-up or delivered to them from a Merchant by Couriers who contract with Mr. Pengu to access the Platform and receive delivery opportunities.</p>
  <p>Mr. Pengu is not a retail store, restaurant, food delivery platform, merchandise delivery platform or food preparation entity. Mr. Pengu is not liable or responsible for Merchants’ compliance with applicable federal, state, or local laws, rules, regulations or standards pertaining to their businesses. In addition, Mr. Pengu does not guarantee the quality of what Merchants sell and does not independently verify, and is not liable for, representations made by Merchants regarding their products on the Platform.</p>
  <p>Mr. Pengu does not provide Courier services. Couriers are independent contractors and not employees, partners, agents, joint ventures, or franchisees of Mr. Pengu. Couriers have entered into independent contractor agreements with Mr. Pengu, which require them to comply with all applicable federal, state, and local laws, rules and regulations. Mr. Pengu shall not be liable or responsible for any delivery services provided by Couriers, or any errors or misrepresentations made by any of them. You hereby acknowledge that Mr. Pengu does not supervise, direct, control, or monitor a Courier’s provision of services and expressly disclaims any responsibility or liability for the services performed.</p>
  <p>As provided in greater detail in these Terms, you agree and acknowledge these material terms:</p>
  <ul>
  <li>The Platform is licensed, not sold to you, and you may use the Platform only as set forth in these Terms;</li>
  <li>Your use of the Platform may be subject to separate third party terms of service and fees, including without limitation your mobile network operator’s (“Carrier”) terms of service and fees, including fees charged for data usage and overage, which are your sole responsibility;</li>
  <li>You consent to the collection, sharing, and use of your personally identifiable information in accordance with Mr. Pengu ‘s <a href="https://mrpengu.com/privacy-policy/">Privacy Policy</a>;</li>
  <li>The Platform is provided “as is” without warranties of any kind, and Mr. Pengu’s liability to you is limited; and</li>
  <li>Disputes arising under these Terms will be resolved by binding individual arbitration.</li>
  </ul>
  <ol>
  <li>Eligibility</li>
  </ol>
  <p>You must be at least eighteen (18) years old to use the Platform. By agreeing to these Terms, you represent and warrant to us: (1) That you are at least eighteen (18) years old; (2) That you have not previously been suspended, banned, or removed from the Platform; and (3) That your registration and your use of the Platform is in compliance with any and all applicable laws and regulations.</p>
  <ol start="2">
  <li>Accounts and Registration</li>
  </ol>
  <p>To access some features of the Platform, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself (such as your name, credit card information, e-mail address, phone number, profile image, or other contact information). You agree that the information you provide to us is accurate, current, and complete, and that you will keep it up-to-date at all times. When you register, you will be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password, and any password for Facebook, Google, or other third-party login. You accept responsibility for all activities that occur under your account. If you have reason to believe that your account is no longer secure, you must immediately notify us via mail. Mr. Pengu will not be liable and you may be liable for losses, damages, liability, expenses, and lawyers’ fees incurred by Mr. Pengu or a third party arising from someone else using your account due to your conduct regardless of whether you have notified us of such unauthorized use. You understand and agree that we may require you to provide information that may be used to confirm your identity and help ensure the security of your account.</p>
  <ol start="3">
  <li>Scope of License</li>
  </ol>
  <p>The Platform is licensed, not sold, to you for use only under the terms of this license. Mr. Pengu reserves all rights not expressly granted to you. Subject to your complete and ongoing compliance with these Terms, Mr. Pengu hereby grants you a personal, limited, non-sublicensable, non-transferable, and revocable license to access the Platform on compatible devices that you own or control, solely for your own personal, non-commercial use, and only in a manner that complies with all legal requirements that apply to you or your use of the Platform. Mr. Pengu may revoke this license at any time, in its sole discretion.</p>
  <p>You may not modify, alter, reproduce, distribute or make the App available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, sell, redistribute or sublicense the App. If you breach these license restrictions, or otherwise exceed the scope of the license granted in these Terms, you may be subject to prosecution and legal damages, as well as liability for infringement of intellectual property rights. These Terms will govern any updates provided to you by Mr. Pengu that replace and/or supplement the original App, unless the upgrade is accompanied by a separate license in which case the terms of that license will govern.</p>
  <ol start="4">
  <li>Payment Terms</li>
  </ol>
  <p>4.1. General Payment Terms</p>
  <p><em>Platform</em></p>
  <p>You understand that the prices for product or menu items displayed through the Platform may differ from the prices offered or published by Merchants for the same product or menu items and/or from prices available at other third-party websites/mobile applications. Prices for product or menu items displayed through the Platform may not be the lowest prices at which the product or menu items are sold.</p>
  <p>Because of the nature of the Platform, Mr. Pengu does not always know how much a Merchant will charge for a particular product or menu item. Where your cart includes product or menu items for which Mr. Pengu does not know the exact price to be charged by the Merchant, Mr. Pengu may designate an estimated subtotal for such product and menu items (the “Estimated Subtotal”). Similarly, where Mr. Pengu does not know the exact price of certain or all fees associated with the order, including any applicable taxes and/or Mr. Pengu fees, we may designate an estimate for such fees (the “Estimated Fees”). If you have included product or menu items in your cart that are subject to Estimated Subtotal and/or Estimated Fees, we will provide you with an estimated total. Merchants may charge more or less than the Estimated Subtotal for products or menu items you order. Similarly, we may charge more or less than the Estimated Fees based upon the final prevailing price of Merchant’s goods. In some cases, we may not be able to provide Estimated Subtotal or Estimated Fees, such as when the merchandise cost is unknown or we are otherwise unable to predict fees. Mr. Pengu reserves the right to determine final prevailing pricing of all product or menu items ordered through the Platform. In cases in which prevailing pricing is different than the Estimated Subtotal and/or Estimated Fees, what you are ultimately charged may be different than the estimated total. You acknowledge and agree to pay the prevailing pricing and fees, even if they differ from the Estimated Subtotal and/or Estimated Fees. Please visit our website&nbsp;to learn more about how product or menu items are priced.</p>
  <p>Certain features of the Platform, including placing orders, may require you to pay fees to Mr. Pengu. Mr. Pengu may change, or add, fees for use of our Platform at any time as we deem necessary or appropriate for our business. You will have an opportunity to review and accept an estimate of the fees that you will be charged, as applicable. The final fees may differ from the estimate. In all cases, you acknowledge and accept that a fee will be charged and you agree to pay said fee. We encourage you to check our Site periodically to learn more about how we charge for the Platform.</p>
  <p>Mr. Pengu has no obligation to itemize its costs, profits or margins when publishing prices on the Platform and reserves the right to change such prices at any time, at its discretion. You are liable for all transaction taxes on the Platform provided under these Terms (other than taxes based on Mr. Pengu ‘s income).</p>
  <p>Mr. Pengu will charge the payment method you specify at the time of purchase or as otherwise specified by you in your account information. We may also place a pre-authorization hold on your payment method, as described in Section 4.3.</p>
  <p>Charges paid by you are final and non-refundable, except as expressly provided in Section 4.2, and will be quoted in the local currency of the location where the order is being delivered or picked up. Except as expressly provided in Section 4.2, Mr. Pengu has no obligation to provide refunds or credits. However, Mr. Pengu, in its sole discretion, may provide users with refunds, courtesy delivery or product credits, or make promotional offers with different features and different rates to any consumers. These credits and offers may be used for future transactions on the Platform. Such credits or offers are non-transferrable, may not be resold, and are not redeemable for cash or other consideration. Mr. Pengu reserves its right to expire, limit, or modify any credits or promotion at any time. If your account is cancelled for any or no reason, you may forfeit any pending, current, or future credits or promotional offers and any other forms of unredeemed value in or associated with your account without prior notice to you.</p>
  <p><em>Referral Program</em></p>
  <p>Mr. Pengu may offer a referral program (“Referral Program”), allowing consumers to earn courtesy delivery or product credits, or other promotional rewards (“Referral Program Rewards”) by inviting their eligible friends to register as new Mr. Pengu consumers using a unique referral code (“Referral Program Codes”). Referral Program Codes must be used for the intended audience and purposes, and may not be sold or transferred in any manner or made available to the general public (whether posted to a public forum or otherwise), unless expressly permitted by Mr. Pengu. Referral Program Rewards are non-transferrable, may not be resold, and are not redeemable for cash or other consideration. You agree we may change the terms and conditions of the Referral Program, terminate the Referral Program, or expire, deduct, limit, or modify your Referral Program Rewards at any time for any reason, including but not limited to, the event that Mr. Pengu determines or believes that your participation in the Referral Program or use or redemption of Referral Program Codes was in error, fraudulent, illegal, or otherwise in violation of these Terms.</p>
  <p>4.2. Unlimited Subscription</p>
  <p>Mr. Pengu Unlimited (“Unlimited”) is offered as a monthly or yearly pre-paid subscription to the Platform on a per account basis. By signing up for Unlimited and providing us with your payment account information, you are signing up to an auto-renewing subscription requiring recurring payments and agree to pay the then-current applicable fee associated with the subscription.</p>
  <p>If you sign up for the monthly subscription, you will be charged your first monthly subscription fee and any applicable taxes on the date you purchase your subscription or, if your subscription includes a free trial, on the day after your free trial ends. Your subscription will automatically continue on a monthly basis, and you will continue to be charged on a monthly basis at the then-current price (including any applicable taxes), until you cancel your subscription or we terminate it. If you sign up for the yearly subscription, you will be charged your first upfront, non-refundable (except as described below) yearly subscription fee and any applicable taxes on the date you purchase your subscription or, if your subscription includes a free trial, on the day after your free trial ends. Your subscription will automatically continue on a yearly basis at the then-current price (including any applicable taxes), and you will continue to be charged on a yearly basis, until you cancel your subscription or we terminate it. You can find your monthly and/or yearly subscription renewal/billing date in your account settings.</p>
  <p>If your subscription includes a free trial, you will not be charged the applicable fee during your free trial. To obtain the free trial you will be required to provide a credit card in order to ensure uninterrupted access to Unlimited and continued use after the expiration of the free trial. Upon completion of your free trial, your subscription will automatically convert into a paid Unlimited subscription and your payment method will be charged the applicable fee unless you have cancelled your Unlimited subscription. You may cancel your Unlimited subscription as described below. You may not receive a notice from us that your free trial has ended or that the paying portion of your Unlimited subscription has begun. You are only permitted one free trial. If your Unlimited subscription is ever terminated for any reason, and you purchase an additional Unlimited subscription, you shall not be eligible for a free trial on any subsequent Unlimited subscriptions.</p>
  <p>We may change the subscription terms or fees at any time on a going forward basis in our discretion. If the pricing for your subscription increases, we will notify you, and provide you an opportunity to change your subscription before applying those changes to your account or charging your payment details in connection with an automatic renewal. The notification will inform you of how long you have to change your subscription before the changes become effective. Your continued use of Unlimited after the changes become effective will constitute your acceptance of the changes. If you do not wish to continue subscribing with the new fees or features, you may cancel your subscription. If you accept the new subscription, its terms and conditions will apply for that renewal and all renewals going forward. For information on the monthly and yearly subscription fees and terms, please visit our website.</p>
  <p>You may cancel your subscription at any time in your account settings or by contacting us via our website. You must cancel your subscription before it renews to avoid billing of the next periodic subscription fees to your account. However, if you cancel a pre-paid yearly or monthly subscription, you will not receive any refund. If you cancel your monthly or yearly subscription, you will be able to use your Unlimited subscription for the remainder of your pre-paid subscription term.</p>
  <p>We may terminate your subscription for Unlimited at our discretion and without any notice. If we cancel your yearly subscription for Unlimited, we will give you a prorated refund based on the amount of time remaining in your pre-paid subscription; provided, however, that Mr. Pengu will not be obligated to grant you a refund if we terminate your account or your subscription because we determine, in our sole discretion, that your actions or your use of the Platform violates these Terms or has harmed another user.</p>
  <p>4.3. Payment Authorization</p>
  <p>You authorize Mr. Pengu to charge all sums for orders that you make to the payment method designated in your account. When you place an order order through Mr. Pengu, a temporary pre-authorization hold is placed on your designated payment method to verify that the card is valid and has funds available for your intended purchase. The amount of this pre-authorization hold may be greater or less than the order total quoted at checkout. However, your payment will be captured up to 24 hours after your order is completed or cancelled. In the event that the pre-authorization is greater than the final amount, the difference will be released after your order is completed or cancelled; depending on your bank, it may take up to 5 business days to receive access to these released funds.</p>
  <p>Mr. Pengu also places an initial temporary pre-authorization hold on each new payment method you add to your account.</p>
  <p>Mr. Pengu reserves the right to request additional information from you if we have reason to believe, in our sole discretion, that a payment method may be fraudulent.</p>
  <p>4.4. Delinquent Accounts</p>
  <p>If payment due on your account is delinquent, we reserve the right to suspend or terminate your access to the Platform; your account information may be sent to a collection agency/debt collector and you may be subject to a collection action, and payment of collection related fees and costs. If any fee for your Unlimited subscription is not paid in a timely manner, we reserve the right to revoke access to your Unlimited subscription and use of Mr. Pengu. If you do not bring your Mr. Pengu balance current after we provide you with notification that your account is in arrears, we reserve the right to suspend or terminate your access to your Unlimited subscription or convert your Unlimited subscription to a non-subscription account. You will be responsible for paying all past due amounts. If you have questions regarding an outstanding balance on your account, please contact us via email.</p>
  <p>If your payment card expires or is replaced by your issuing bank, the card network may provide us with updated card details associated with the same account. We may use these new details in order to help prevent any interruption to the Platform. If you would like to use a different payment method or remove a saved payment method from your account, please visit your account settings to update your billing information.</p>
  <p>4.5. Consumer Not Available</p>
  <p>Mr. Pengu reserves the right to charge you the full order amount, including any Mr. Pengu fees, if you are not at the designated delivery location when the Courier arrives to complete the delivery or if you fail to pick up an order from a Merchant.</p>
  <p>4.6. Cancelled Orders</p>
  <p>If you cancel your order, you may be charged depending on what stage the order was in when you cancelled. You will be notified of any applicable charges before you complete your cancellation. You can learn more about order cancellations in our website.</p>
  <p>4.7. Returned Items</p>
  <p>If an item has to be returned for any reason, you may be subject to a non-refundable $15 return/restocking fee. For alcohol items, the Courier reserves the right, at his or her discretion, to refuse delivery and return the item(s) if the name on your ID does not match the name on your order, if you are not at least twenty-one (21) years old (“Legal Age”), if you cannot provide a bona-fide government-issued photo identification that shows you are of Legal Age, or if you are visibly intoxicated.</p>
  <ol start="5">
  <li>Third-Party Interactions</li>
  </ol>
  <p>5.1. Third-Party Providers</p>
  <p>During use of the Platform, you may purchase goods and services from third-party Merchants through the Platform. Any such activity, and any interactions, disputes, terms, conditions, warranties or representations associated with that activity, is solely between you and the applicable third-party Merchant. Mr. Pengu and its licensors shall have no liability, obligation or responsibility for any purchase or transaction between you and any third-party provider. In no event shall Mr. Pengu or its licensors be responsible for any content, products, services or other materials on or available from third-party sites or third-party providers. Certain third-party providers of goods and/or services may require your agreement to additional or different terms and conditions prior to your use of or access to such goods or services, and Mr. Pengu disclaims any and all responsibility or liability arising from such agreements between you and a third party.</p>
  <p>5.2. Couriers</p>
  <p>The Platform enables you to engage third-party Couriers to provide delivery services. Any interactions or disputes between you and a Courier are solely between you and that Courier. Mr. Pengu and its licensors shall have no liability, obligation or responsibility for any interaction between you and any Courier.</p>
  <p>5.3. Third-Party Advertising</p>
  <p>The Platform may contain third-party advertising and marketing. By agreeing to these Terms you agree to receive such advertising and marketing.</p>
  <p>5.4. Links to Third Party Sites</p>
  <p>The Platform may contain links to third-party websites. Linked websites are not under our control, and we are not responsible for their content.</p>
  <ol start="6">
  <li>Your Use of the Platform</li>
  </ol>
  <p>In order to use the Platform, you agree to the following:</p>
  <ul>
  <li>The Platform, including any content that forms part of the Platform, contains proprietary content, information and material that is protected by applicable intellectual property and other laws, including copyright;</li>
  <li>You will not violate, or encourage others to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property right, or otherwise engage in the unauthorized use of any proprietary content, information or materials;</li>
  <li>Unless expressly permitted, you may not alter, modify, create derivative works of, sell, license or in any way exploit any part of the Platform, and you agree not to copy, reproduce, distribute, publish, display, perform, transmit, stream or broadcast any part of the Platform without prior written authorization;</li>
  <li>You agree not to bypass any security or other features of the Platform designed to control the manner in which the Platform is used, harvest or mine content from the Platform, or otherwise access or use the Platform in a manner inconsistent with individual human use;</li>
  <li>You agree not to perform any fraudulent activity, including impersonating any person or entity, or accessing any other Platform account without permission;</li>
  <li>You agree not to decipher, reverse engineer, decompile or disassemble the Platform, or the software used to provide the Platform, in whole or in part, or authorize, direct, or cause a third party to do so;</li>
  <li>You agree not to use, display, mirror, frame or utilize framing techniques to enclose the Platform, or any portion thereof, unless and solely to the extent Mr. Pengu makes available the means for embedding any part of the Platform;</li>
  <li>You agree not to access, tamper with, or use non-public areas of the Platform, Mr. Pengu ‘s (and its hosting company’s) computer systems and infrastructure, or the technical delivery systems of Mr. Pengu ‘s providers;</li>
  <li>You agree not to use any robot, spambot, spider, crawler, scraper or other automated means or interface not provided by us to access the Platform or to extract data;</li>
  <li>You agree not to use the Platform in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party, and that Mr. Pengu is not in any way responsible for any such use by you, nor for any harassing, threatening, defamatory, offensive or illegal messages or transmissions that you may receive as a result of using the Platform;</li>
  <li>You agree that your use of the Platform may incur third-party fees, such as fees charged by your Carrier for data usage, and may be subject to third-party terms, such as your Carrier’s terms of service, and you agree to pay all such fees and abide by all such terms; and</li>
  <li>You agree not to introduce viruses, time-bombs, worms, cancelbots, trojan horses and/or other harmful code into the Platform.</li>
  </ul>
  <p><strong>Transactions involving Alcohol.</strong>&nbsp;Alcoholic beverages (including but not limited to beer, wine, cider, and spirits, as applicable; all referred to as “Alcoholic Beverages”) may only be purchased by consumers who are of Legal Age. If you are a consumer, you expressly represent and warrant that: (i) you are of Legal Age; and (ii) you will provide bona fide government-issued photo identification to your Courier upon delivery to you. Valid forms of identification include but are not limited to: (i) a valid motor vehicle operator’s license, (ii) a passport issued by the Greek Government or by a foreign government, or (iii) a valid identification card issued to a member of the Armed Forces that includes a date of birth and a picture, showing your Legal Age. Deliveries of Alcoholic Beverages may not be made to anyone who is intoxicated, regardless of his or her age. You further understand and acknowledge that neither Mr. Pengu nor the Courier can accept your order of Alcoholic Beverages, and the order will only be delivered if the third-party Merchant accepts your order.</p>
  <p>You agree not to do any of the acts described in this Section 6, or to assist or permit any person in engaging in any of the acts described in this Section 6.</p>
  <ol start="7">
  <li>Consent to Use of Data</li>
  </ol>
  <p>Please see Mr. Pengu ‘s Privacy Policy, for more information regarding information Mr. Pengu collects, and how it uses and shares that information.</p>
  <ol start="8">
  <li>Intellectual Property Ownership</li>
  </ol>
  <p>The Platform, and the media and materials contained in the Platform, including all intellectual property rights in the Platform, are the sole and exclusive property of Mr. Pengu and its licensors. Except for the limited license expressly granted by and to you under these Terms, no other rights, licenses, or immunities are granted or shall be deemed to be granted under these Terms, either expressly, or by implication, estoppel or otherwise. All rights not expressly granted by Mr. Pengu in these Terms are expressly reserved.</p>
  <ol start="9">
  <li>Content You Provide through the Platform</li>
  </ol>
  <p>9.1. Content You Provide</p>
  <p>You may be able to submit, post, upload, denote, or otherwise make available (collectively, “Post”) photographs, video clips, reviews, ratings, favorites, liked items, bookmarked Merchants, questions, comments, public messages, ideas, designs, concepts, inventions, feedback, and other content (collectively, “User Content”) (that may or may not be viewable by other users) through the Platform or through other communications with you, including, without limitation, through text (“SMS”) or multimedia (“MMS”) messages (“Interactive Areas”).</p>
  <p>9.2. Use of Your Content</p>
  <p>You acknowledge that when you Post User Content on or through the Platform, the User Content shall be deemed, and shall remain Mr. Pengu ‘s property. Mr. Pengu does not provide any compensation for User Content that you Post on or through the Platform. You agree that User Content that you Post on or through the Platform shall be deemed to be non-confidential and non-proprietary, and Mr. Pengu shall have no obligation of any kind with respect to such information. When you Post User Content on or through the Platform, you grant Mr. Pengu a world-wide, perpetual, irrevocable, royalty-free, non-exclusive, and sub-licensable license to use, copy, distribute, reproduce, modify, edit, adapt, publicly perform, publicly display, translate, create derivative works from, sell, lease, transmit, communicate to the public, disassemble, and publish such User Content in connection with Mr. Pengu ‘s or its partners’ or affiliates’ business, in whole or in part, in any format or medium now known or developed in the future, for any purpose whatsoever, unless expressly agreed otherwise in writing by Mr. Pengu, including without limitation for promoting and redistributing part or all of the Platform (and derivative works thereof) in any media formats and through any media channels. You further grant Mr. Pengu a license to use your username and/or other user profile information, including, without limitation, your ratings history and how long you have been a Mr. Pengu consumer, to attribute User Content to you, if we choose to do so. Further, Mr. Pengu shall be free to use any ideas, concepts, know-how or techniques contained in User Content for any purpose whatsoever in connection with our business or the business of our partners or affiliates, without notice to, approval by, or compensation to you, including but not limited to developing, manufacturing and marketing products incorporating such information. In the interest of clarity, the license granted to Mr. Pengu shall survive termination of the Platform or your account. Notwithstanding the foregoing, our use of your personal data shall be governed by the Mr. Pengu Privacy Policy.</p>
  <p>9.3. User Content Representations</p>
  <p>You acknowledge and agree that all User Content that you Post is your sole responsibility. You represent that you have all required rights to Post or transmit such User Content without violation of any third-party rights. You understand that Mr. Pengu does not control, and is not responsible for, User Content, and that by using the Platform, you may be exposed to User Content from other users that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. Please also note that User Content may contain typographical errors, other inadvertent errors or inaccuracies. You agree that you will indemnify, defend, and hold harmless Mr. Pengu for all claims resulting from User Content you Post. We reserve the right, at our own expense, to assume the exclusive defense and control of such disputes, and in any event you will cooperate with us in asserting any available defenses.</p>
  <p>9.4. User Content Review</p>
  <p>You acknowledge and agree that Mr. Pengu and its designees may or may not (but do not assume any obligation to), at Mr. Pengu ‘s discretion, pre-screen User Content before its appearance on the Platform. You further acknowledge and agree that Mr. Pengu reserves the right (but does not assume the obligation) in its sole discretion to reject, move, edit or remove any User Content that is contributed to the Platform. Additionally, Mr. Pengu has the right to remove any User Content that violates these Terms or is otherwise objectionable in Mr. Pengu ‘s sole discretion. You acknowledge and agree that Mr. Pengu does not verify, adopt, ratify, or sanction User Content, and you agree that you must evaluate and bear all risks associated with your use of User Content or your reliance on the accuracy, completeness, or usefulness of User Content.</p>
  <p>9.5. Ratings and Reviews</p>
  <p>The Platform and other Interactive Areas may allow you to rate (“Ratings”) and Post reviews (“Reviews”) of Merchants. Such Ratings and Reviews are considered User Content and are governed by these Terms, including, without limitation, your agreement regarding your use of the Platform (Section 6). Ratings and Reviews are not endorsed by Mr. Pengu, and do not represent the views of Mr. Pengu or of any affiliate or partner of Mr. Pengu. Mr. Pengu does not assume liability for Ratings and Reviews or for any claims, liabilities, or losses resulting from any Ratings and Reviews. We strive to maintain a high level of integrity with our Ratings and Reviews and other User Content. Therefore, all Ratings and Reviews must comply with the following criteria: (1) you must have had first-hand experience with the Merchant within the 7-day period prior to your Posting a Rating or Review; (2) you may not have a proprietary or other affiliation with either the Merchant or any of its competitors; (3) you may not draw any legal conclusions regarding the Merchant’s products, services, or conduct; (4) you may not promote or criticize a Merchant other than the one being rated or reviewed; (4) you may not include others’ personal information; and (5) your Rating or Review must otherwise comply with these Terms. Any Rating and/or Review that we determine, in our sole discretion, could diminish the integrity of the Ratings and Reviews, and/or the Platform may be removed or excluded by us without notice.</p>
  <ol start="10">
  <li>Communications</li>
  </ol>
  <p>10.1. Text Messaging</p>
  <p>By using the Platform, you agree that Mr. Pengu and those acting on its behalf may send you text (SMS) messages at the phone number you provided us. These messages may include operational messages about your use of the Platform, as well as marketing or other promotional messages. You will not be able to use the Platform without agreeing to receive operational text messages. You may opt-out of receiving marketing text messages at any time by sending an email. You may continue to receive text messages for a short period while Mr. Pengu processes your request, and you may also receive text messages confirming the receipt of your opt-out request. If you do not want to receive operational text messages from Mr. Pengu, do not place orders through the Platform. Text messages may be sent using an automatic telephone dialing system. Your agreement to receive marketing texts is not a condition of any purchase or use of the Platform. If you change or deactivate the phone number you provided to Mr. Pengu, you must update your account information to help prevent us from inadvertently communicating with anyone who acquires your old number. Standard data and message rates may apply for SMS and MMS alerts, whether you send or receive such messages. Please contact your Carrier for details.</p>
  <p>10.2. Push Notifications</p>
  <p>When you install our App on your mobile device you agree to receive push notifications, which are messages an app sends you on your mobile device even when the app is not on. You can turn off notifications by visiting your mobile device’s “settings” page.</p>
  <p>10.3. Email</p>
  <p>Mr. Pengu may send you emails concerning our products and services, as well as those of third parties. You may opt-out of promotional emails by following the unsubscribe instructions in a promotional email.</p>
  <p>10.4. E-SIGN Disclosure</p>
  <p>By agreeing to receive text messages, you also consent to the use of an electronic record to document your agreement. You may withdraw your consent to the use of the electronic record by contacting us via mail&nbsp;with “Revoke Electronic Consent” in the subject line. To view and retain a copy of this disclosure or any information regarding your enrollment in this program, you will need (i) a device (such as a computer or mobile phone) with a web browser and Internet access and (ii) either a printer or storage space on such device. For a free paper copy, or to update our records of your contact information, please contact us via mail&nbsp;with contact information and the address for delivery.</p>
  <p>10.5. Notice of Intellectual Property Infringement</p>
  <p>In accordance with the Digital Millennium Copyright Act (DMCA) and other applicable law, it is the policy of Mr. Pengu, in appropriate circumstances, to terminate the registration account of a user who is deemed to infringe third-party intellectual property rights and/or to remove user content that is deemed to be infringing. If you believe that your work has been copied in a way that constitutes copyright infringement and is displayed on the Platform, please provide substantially the following information to our Copyright Agent:</p>
  <ul>
  <li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
  <li>A description of your copyrighted work or other intellectual property that you claim has been infringed;</li>
  <li>A description of where the material you claim is infringing is located on the Services (providing us with website URL is the quickest way to help us locate content quickly);</li>
  <li>Your address, telephone number, and email address;</li>
  <li>A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
  <li>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.</li>
  </ul>
  <p>Please note that the above contact information is for intellectual property infringement notices only. DO NOT CONTACT OUR COPYRIGHT AGENT FOR OTHER INQUIRIES OR QUESTIONS. For other inquiries or questions, please contact us via mail. Please also note that, pursuant to Section 512(f) of the Copyright Act, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>
  <ol start="11">
  <li>Indemnity</li>
  </ol>
  <p>You are responsible for your use of the Platform, and you agree to defend (at Mr. Pengu ‘s option), indemnify, and hold harmless Mr. Pengu and its officers, directors, employees, contractors, consultants, affiliates, investors, service providers, business partners, subsidiaries and agents from and against every claim, liability, damage, loss, and expense, including reasonable attorneys’ fees and costs, arising out of or in any way connected with:</p>
  <ul>
  <li>Your violation of any of these Terms, any representation, warranty, or agreement referenced in these Terms, or any applicable law or regulation;</li>
  <li>Your violation of any third-party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; or</li>
  <li>Any dispute or issue between you and any third party, including any Courier, Merchant, or other third-party.</li>
  </ul>
  <p>Mr. Pengu reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (without limiting your indemnification obligations) and you agree to cooperate with our defense of that claim. If the defense or settlement is assumed by you, Mr. Pengu may at any time thereafter elect to take over control of the defense and settlement of the claim. You must not settle any claim without Mr. Pengu ‘s prior written consent.</p>
  <ol start="12">
  <li>Disclaimer of Warranties</li>
  </ol>
  <p>YOUR USE OF THE PLATFORM IS AT YOUR SOLE RISK. THE PLATFORM IS PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS, ARE HEREBY DISCLAIMED BY MR. PENGU TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. MR. PENGU MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE PLATFORM. MR. PENGU DOES NOT REPRESENT OR WARRANT THAT THE USE OF THE PLATFORM WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA; THAT THE PLATFORM OR ANY PRODUCTS OR MATERIALS OBTAINED BY YOU THROUGH THE PLATFORM WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS; OR THAT THE PLATFORM OR THE SERVER(S) THAT MAKE THE PLATFORM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
  <ol>
  <li>PENGU ‘S PLATFORM MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. MR. PENGU IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.</li>
  <li>PENGU RELIES UPON MERCHANTS, INCLUDING, BUT NOT LIMITED TO, RESTAURANTS AND OTHER THIRD-PARTY FOOD AND BEVERAGE PROVIDERS AND RETAILERS TO PROVIDE ACCURATE ALLERGEN AND DIETARY INFORMATION AND GENERAL PRODUCT SAFETY. MR. PENGU DOES NOT REPRESENT OR WARRANT THAT SUCH INFORMATION ACCESSIBLE THROUGH THE PLATFORM IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE, INCLUDING WITHOUT LIMITATION MENUS, NUTRITIONAL AND ALLERGEN INFORMATION, PHOTOS, FOOD QUALITY OR DESCRIPTIONS, PRICING, HOURS OF OPERATION, OR REVIEWS. ALL CONTENT IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY. THE RELIANCE ON ANY INFORMATION PROVIDED THROUGH THE PLATFORM IS SOLELY AT YOUR OWN RISK, INCLUDING WITHOUT LIMITATION NUTRITIONAL AND ALLERGEN INFORMATION.</li>
  <li>PENGU DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR PLATFORM ADVERTISED OR OFFERED BY A MERCHANT OR OTHER THIRD PARTY THROUGH THE PLATFORM OR ANY HYPERLINKED WEBSITE OR THIRD-PARTY SERVICE, AND MR. PENGU WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</li>
  <li>Limitation of Liability</li>
  </ol>
  <p>IN NO EVENT SHALL MR. PENGU ‘S AGGREGATE LIABILITY EXCEED THE MR. PENGU FEES ACTUALLY PAID BY YOU TO MR. PENGU IN THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM OR $100, WHICHEVER IS LESS. IN NO EVENT SHALL MR. PENGU AND/OR ITS LICENSORS BE LIABLE TO ANYONE FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING PERSONAL INJURY, LOSS OF DATA, REVENUE, PROFITS, REPUTATION, USE OR OTHER ECONOMIC ADVANTAGE) EVEN IF MR. PENGU AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
  <p>THIS LIMITATION OF LIABILITY SECTION APPLIES FULLY IN ALL STATES, INCLUDING RESIDENTS OF NEW JERSEY.</p>
  <p>THE PLATFORM CONNECTS YOU TO COURIERS AND MERCHANTS FOR THE PURPOSES OF FACILITATING COURIER AND PRODUCT FULFILLMENT SERVICES. MR. PENGU WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY COURIERS OR MERCHANTS, AND YOU EXPRESSLY WAIVE AND RELEASE MR. PENGU FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE COURIERS OR MERCHANTS. MR. PENGU WILL NOT ASSESS THE QUALITY, SAFETY, OR LEGALITY OF THE ITEMS PROVIDED BY MERCHANTS ON THE PLATFORM, AND YOU EXPRESSLY WAIVE AND RELEASE MR. PENGU FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO MERCHANTS, AND THE ITEMS THEY PROVIDE. MR. PENGU WILL NOT BE A PARTY TO DISPUTES OR NEGOTIATIONS OF DISPUTES, BETWEEN YOU AND ANY COURIERS, OR MERCHANTS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING SERVICES OFFERED VIA THE PLATFORM (WITH ALL THEIR IMPLICATIONS) RESTS SOLELY WITH YOU. IN ADDITION, WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTIES, AND YOU EXPRESSLY WAIVE AND RELEASE MR. PENGU FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE PLATFORM, OR IN ANY WAY RELATED TO THE THIRD PARTIES INTRODUCED TO YOU BY THE PLATFORM.</p>
  <ol start="14">
  <li>Notice</li>
  </ol>
  <p>Mr. Pengu may give notice by any means of communication reasonably anticipated to notify you of the information provided. You agree that all notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing or be delivered in a particular manner. You agree that you have the ability to store such electronic communications such that they remain accessible to you in an unchanged form. By way of example only, such communication may be a general notice on the Platform or via email to the email address listed on your Mr. Pengu account. It is your obligation to update your account information so that we may contact you as may be necessary. Such notice shall be deemed to have been given 48 hours after dispatch. If physical notice (e.g., US Mail) is used, then such notice shall be deemed to have been given 7 days after dispatch.</p>
  <p>Except as explicitly described in the Dispute Resolution and Arbitration section, you may give notice to Mr. Pengu (such notice shall be deemed given when received by Mr. Pengu) at any time by mail.</p>
  <ol start="15">
  <li>Assignment</li>
  </ol>
  <p>You may not assign or transfer these Terms or your rights under these Terms, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms in whole or in part at any time to any entity without your notice or consent. Any purported assignment by you in violation of this section shall be void.</p>
  <ol start="16">
  <li>Term and Termination of Agreement</li>
  </ol>
  <p>These Terms are effective until terminated by you or Mr. Pengu as described below. Your rights under these Terms will terminate automatically without notice from Mr. Pengu if you fail to comply with any of these Terms (including by violating any license restriction contained in these Terms). In addition, Mr. Pengu may in its sole discretion terminate your user account on the Platform or suspend or terminate your access to the Platform at any time without notice. We also reserve the right to modify or discontinue the Platform at any time (including by limiting or discontinuing certain features of the Platform) without notice to you. We will have no liability whatsoever on account of any change to the Platform or any suspension or termination of your access to or use of the Platform. You may terminate these Terms at any time by closing your account, uninstalling the App, and ceasing use of the Platform. Sections 4.4, 5, 7-17, and 19-21 survive termination of your account or these Terms.</p>
  <ol start="17">
  <li>Dispute Resolution and Arbitration</li>
  </ol>
  <p>17.1. Disputes</p>
  <p>Mr. Pengu is not a party to, has no involvement or interest in, makes no representations or warranties as to, and has no responsibility or liability with respect to any communications, transactions, interactions, disputes or any relations whatsoever between you and any other user, any Courier, or Merchant, or other third party. Disputes between you and Mr. Pengu are subject to this Section 17. You and Mr. Pengu agree that these Terms affect interstate commerce and that the Federal Arbitration Act governs the interpretation and enforcement of the arbitration provisions in these Terms.</p>
  <p>17.2. Generally</p>
  <p>In the interest of resolving Disputes between you and Mr. Pengu in the most expedient and cost effective manner, you and Mr. Pengu agree that every Dispute arising in connection with these Terms will be resolved by binding individual arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, and can be subject to very limited review by courts. While the parties will be permitted to engage in discovery or exchange of non-privileged information relevant to the dispute, arbitration may allow for more limited discovery allowed for in court. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of these Terms, the Platform, or your relationship with us, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms.</p>
  <p><strong>YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND MR.PENGU ARE EACH WAIVING THE RIGHT TO GO TO COURT OR TO PARTICIPATE IN A CLASS OR REPRESENTATIVE ACTION.</strong></p>
  <p>17.3. Exceptions</p>
  <p>Despite the provisions of the paragraph directly above, we both agree that nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either of us to: (1) Bring an individual action in small claims court; (2) Pursue an enforcement action through the applicable federal, state, or local agency if that action is available; or (3) File suit in a court of law to address an intellectual property infringement claim.</p>
  <p>17.4. Arbitrator</p>
  <p>Any arbitration between you and Mr. Pengu shall be conducted by a single arbitrator, governed by JAMS pursuant to its Comprehensive Arbitration Rules &amp; Procedures,</p>
  <p>17.5. Notice Process</p>
  <p>A party who intends to seek arbitration must first send a written notice of the Dispute to the other, by certified mail or Federal Express (signature required), or if we do not have a physical address on file for you, by electronic mail (“Notice”).</p>
  <p>The Notice must: (1) Describe the nature and basis of the claim or dispute; and (2) Set forth the specific relief sought (“Demand”).</p>
  <p>We agree to use good faith efforts to resolve the claim directly, but if we do not reach an agreement to do so within thirty (30) days after the Notice is received, you or Mr. Pengu may commence an arbitration proceeding. To start an arbitration, you must do the following: (1) Write a Demand for Arbitration that includes a description of the claim and the amount of damages you seek to recover. (2) Send three copies of the Demand for Arbitration, plus the filing fee, to the authority in charge and (3) Send one copy of the Demand for Arbitration to Mr. Pengu at the following address:</p>
  <p>3rd Floor, 282 Leoforos Kifisias, Chalandri, 152 32 Athens, Greece. Telephone: +30 21 0683 5092.</p>
  <p>During the arbitration, the amount of any settlement offer made by you or Mr. Pengu must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any.</p>
  <p>17.6. Fees</p>
  <p>If you commence arbitration in accordance with these Terms, you will be required to pay a fee to initiate the arbitration. If the arbitrator finds the arbitration to be non-frivolous, Mr. Pengu will pay all other fees invoiced by the authorities, including filing fees and arbitrator and hearing expenses. You are responsible for your own attorneys’ fees unless the arbitration rules and/or applicable law provide otherwise.</p>
  <p>If you are a resident of the Greece, arbitration may take place in the county where you reside at the time of filing. For individuals residing outside the Greece, arbitration shall be initiated in Greece. You and Mr. Pengu further agree to submit to the personal jurisdiction of any federal or state court in Athens, Greece in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator. If a claim is for 10,000€ or less, you may choose whether the arbitration will be conducted: (1) Solely on the basis of documents submitted to the arbitrator; or (2) Through a non-appearance based telephone hearing.</p>
  <p>If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the authorities. In that case, you agree to reimburse Mr. Pengu for all monies previously disbursed by it that are otherwise your obligation to pay under the Government’s Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based.</p>
  <p>The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within fourteen (14) days of the arbitrator’s ruling on the merits.</p>
  <p>17.7. No Class or Representative Actions</p>
  <p><strong>YOU AND MR. PENGU AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</strong></p>
  <p>Further, unless both you and Mr. Pengu agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding. If any court or arbitrator determines that this “No Class or Representative Actions” section is void or unenforceable for any reason or that an arbitration can proceed on a class or representative basis, then the arbitration provisions set forth above shall be deemed null and void in their entirety and the parties shall be deemed to have not agreed to arbitrate disputes.</p>
  <p>17.8. 30-Day Right to Opt Out</p>
  <p>You have the right to opt out and not be bound by the arbitration and class action waiver provisions set forth above by submitting a request via e-mail. The notice must be sent within thirty (30) days of your creating an account with Mr. Pengu or the effective date of the first set of Terms containing a Dispute Resolution and Arbitration section, whichever is later; otherwise, you shall be bound to arbitrate disputes in accordance with the terms of these paragraphs. If you opt out of these arbitration provisions, Mr. Pengu also will not be bound by them. NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN, NOTHING IN THIS AGREEMENT SHALL SUPERSEDE, AMEND, OR MODIFY THE TERMS OF ANY SEPARATE AGREEMENT(S) BETWEEN YOU AND MR. PENGU RELATING TO YOUR WORK AS AN EMPLOYEE OR USE OF THE PLATFORM AS AN INDEPENDENT CONTRACTOR, INCLUDING WITHOUT LIMITATION, ANY INDEPENDENT CONTRACTOR AGREEMENT (INCLUDING BUT NOT LIMITED TO THE FLEET AGREEMENT) GOVERNING YOUR SERVICES AS A CONTRACTOR. FOR THE AVOIDANCE OF DOUBT, IF YOU ARE AN INDEPENDENT CONTRACTOR, OPTING OUT OF THE ARBITRATION AGREEMENT SET FORTH IN THIS SECTION 17 WILL NOT AFFECT ANY AGREEMENT BY YOU TO ARBITRATE DISPUTES COVERED BY YOUR INDEPENDENT CONTRACTOR AGREEMENT (INCLUDING BUT NOT LIMITED TO THE FLEET AGREEMENT) WITH MR PENGU.</p>
  <p>17.9. Modifications</p>
  <p>Except for inconsequential changes that do not affect any rights or obligations herein, Mr. Pengu will provide thirty (30) days’ notice of any changes to this section by posting on the Platform, sending you a message, or otherwise notifying you when you are logged into your account. Amendments will become effective thirty (30) days after they are posted on the Platform or sent to you, or otherwise notified when you are logged into your account. Changes to this section will otherwise apply prospectively only to claims arising after the thirtieth (30th) day. If a court or arbitrator decides that this subsection on “Modifications” is not enforceable or valid, then this subsection shall be severed from the section entitled “Dispute Resolution and Arbitration,” and the court or arbitrator shall apply the first Dispute Resolution and Arbitration section in existence after you began using the Platform. You may otherwise reject the change by sending us written notice within thirty (30) days of the change to Mr. Pengu ‘s address for Notice, in which case your account with Mr. Pengu will be immediately terminated and this arbitration provision, as in effect immediately prior to the amendments you reject, will survive.</p>
  <ol start="18">
  <li>Modification of these Terms</li>
  </ol>
  <p>Except as explicitly described in the Dispute Resolution and Arbitration section, we reserve the right to update or modify the Terms at any time without prior notice, and such changes will be effective immediately upon being posted through the Platform, except as set forth below. These Terms identify the date of last update. Except as explicitly described in the Dispute Resolution and Arbitration section, your use of the Platform following any such change constitutes your agreement to be bound by the modified Terms. In the case of material changes to these Terms, we will make reasonable efforts to notify you of the change, such as through sending an email to the address you may have used to register for an account, through a pop-up window on the Platform, or other similar mechanism.</p>
  <p>You acknowledge and agree that if Mr. Pengu modifies any provision of these Terms (including any information referenced at hyperlinks), other than the Dispute Resolution and Arbitration section herein, you will not have a renewed opportunity to opt out of arbitration. You further acknowledge and agrees that unless the Dispute Resolution and Arbitration section herein is materially different from any prior arbitration provision with Mr. Pengu to which you may be bound, your acceptance of these Terms does not create a renewed opportunity to opt out of arbitration (if applicable).</p>
  <p>Except as explicitly described in the Dispute Resolution and Arbitration section, material changes to these Terms will be effective upon the earlier of: (1) Your first use of the Platform with actual notice of such change, or (2) thirty (30) days from posting of such change.</p>
  <p>Disputes arising under these Terms will be resolved in accordance with the version of the Terms in place at the time the dispute arose. We encourage you to review these Terms frequently to stay informed of the latest modifications.</p>
  <ol start="19">
  <li>Confidentiality</li>
  </ol>
  <p>You acknowledge and agree that when using the Platform, you may have direct or indirect access or exposure to Mr. Pengu ‘s confidential information (“Confidential Information”). Confidential Information includes Mr. Pengu ‘s data, provider IDs, user information, delivery recipient information, delivery provider information, package information, and the transaction volume, marketing and business plans, business, financial, technical, operational and such other nonpublic information (whether disclosed in writing or verbally) that Mr. Pengu designates as being proprietary or confidential or that you should reasonably know to treat as confidential.</p>
  <p>You acknowledge and agree that: (1) all Confidential Information shall remain the exclusive property of the Mr. Pengu; (2) you shall not use Confidential Information for any purpose except in furtherance of your use of the Platform; (3) you shall not disclose Confidential Information to any third party; and (d) you shall not store or keep Confidential Information and shall return or destroy (with confirmation of destruction) all Confidential Information upon the termination of your use of the Platform or at the request of Mr. Pengu.</p>
  <p>Notwithstanding the foregoing, Confidential Information shall not include any information to the extent it: (1) is or becomes part of the public domain through no action or omission by you; (2) was possessed by you prior to your use of the Platform without an obligation of confidentiality; or (3) is disclosed to you by a third party having no obligation of confidentiality with respect thereto.</p>
  <ol start="20">
  <li>General</li>
  </ol>
  <p>Governing Law. These Terms are governed by the laws of the Greek Government without regard to conflict of law principles. If a lawsuit or court proceeding is permitted under these Terms, you and Mr. Pengu agree to submit to the personal and exclusive jurisdiction of the state courts and federal courts located within Greece for the purpose of litigating any Dispute. We operate the Platform from our offices in Athens, and we make no representation that materials included in the Platform are appropriate or available for use in other locations. No joint venture, partnership, employment, or agency relationship exists between you, Mr. Pengu or any third-party provider as a result of the Terms or use of the Platform.</p>
  <p>Waiver and Severability. Except as explicitly described in the Dispute Resolution and Arbitration section, if any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. The failure of Mr. Pengu to enforce any right or provision in these Terms shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Mr. Pengu in writing.</p>
  <p>Entire Agreement. These Terms comprise the entire agreement between you and Mr. Pengu and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between the parties regarding the subject matter contained in these Terms.</p>
  <ol start="21">
  <li>Notice Regarding Apple</li>
  </ol>
  <p>To the extent that you are using our mobile applications on an iOS device, you further acknowledge and agree to the terms of this Section 22. You acknowledge that these Terms are between you and Mr. Pengu only, not with Apple Inc. (“Apple”), and Apple is not responsible for the Platform and the content thereof.</p>
  <p>Apple has no obligation whatsoever to furnish any maintenance and support platforms with respect to the Platform. In the event of any failure of the Platform to conform to any applicable warranty, you may notify Apple and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation whatsoever with respect to the Platform.</p>
  <p>Apple is not responsible for addressing any claims by you or any third party relating to the Platform or your possession and/or use of the Platform, including, but not limited to: (1) Product liability claims; (2) Any claim that the Platform fails to conform to any applicable legal or regulatory requirement; and (3) Claims arising under consumer protection or similar legislation.</p>
  <p>Apple is not responsible for the investigation, defense, settlement and discharge of any third-party claim that the Platform and/or your possession and use of the mobile application infringes that third party’s intellectual property rights. You agree to comply with any applicable third-party terms when using the Platform. Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms.</p>

  </div>
`;
